# Generated by Django 3.0.8 on 2020-08-20 15:39

import apps.v1.cervic_model.models
import apps.v1.common.tools
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cervic_model', '0010_aimodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aimodel',
            options={'verbose_name': 'AI Model', 'verbose_name_plural': 'AI Models'},
        ),
        migrations.AlterField(
            model_name='aimodel',
            name='model',
            field=models.FileField(upload_to=apps.v1.cervic_model.models.get_ai_model_name, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pt'])]),
        ),
        migrations.AlterField(
            model_name='aimodel',
            name='name',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator(message='Must contain at least one of alphanumeric or underscore characters', regex='^\\w+$'), django.core.validators.RegexValidator(message='You can\'t name the model starts with "chosen"', regex='^(?!.*((?i)chosen)).*')]),
        ),
        migrations.AlterField(
            model_name='cervicclassification',
            name='image',
            field=models.ImageField(upload_to=apps.v1.common.tools.DefaultFileNameFormat(prefix='classifications')),
        ),
        migrations.AlterField(
            model_name='cervicclassification',
            name='result',
            field=models.IntegerField(choices=[(0, 'Negative'), (1, 'Positive'), (98, 'Unknown'), (99, 'Unclassified')], default=99),
        ),
    ]
